CREATE TABLE TB_ACCESS_LEVEL (
  ID BIGINT NOT NULL,
   AUTHORITY VARCHAR(255),
   CONSTRAINT PK_TB_ACCESS_LEVEL PRIMARY KEY (ID)
);

CREATE TABLE TB_ADDRESS (
  ID BIGINT NOT NULL,
   ZIP_CODE VARCHAR(8),
   PUBLIC_AREA VARCHAR(255),
   DISTRICT VARCHAR(255),
   COMPLEMENT VARCHAR(255),
   CITY VARCHAR(255),
   UF VARCHAR(2),
   CONSTRAINT PK_TB_ADDRESS PRIMARY KEY (ID)
);

CREATE TABLE TB_CUSTOMER (
  ID BIGINT NOT NULL,
   USER_ID BIGINT,
   CONSTRAINT PK_TB_CUSTOMER PRIMARY KEY (ID)
);

CREATE TABLE TB_EMPLOYEE_TREATMENT (
  EMPLOYEE_ID BIGINT NOT NULL,
   TREATMENT_ID BIGINT NOT NULL,
   CONSTRAINT PK_TB_EMPLOYEE_TREATMENT PRIMARY KEY (EMPLOYEE_ID, TREATMENT_ID)
);

CREATE TABLE TB_EMPLOYEE (
  ID BIGINT NOT NULL,
   USER_ID BIGINT,
   IS_ACTIVE BOOLEAN,
   CONSTRAINT PK_TB_EMPLOYEE PRIMARY KEY (ID)
);

CREATE TABLE TB_EXPENSE (
  ID BIGINT NOT NULL,
   DESCRIPTION VARCHAR(255),
   IS_ACTIVE BOOLEAN,
   CONSTRAINT PK_TB_EXPENSE PRIMARY KEY (ID)
);

CREATE TABLE TB_MESSAGE_TEMPLATE (
  ID BIGINT NOT NULL,
   TITLE VARCHAR(255),
   MESSAGE VARCHAR(255),
   IS_ACTIVE BOOLEAN,
   CONSTRAINT PK_TB_MESSAGE_TEMPLATE PRIMARY KEY (ID)
);

CREATE TABLE TB_PAYMENT_METHOD (
  ID BIGINT NOT NULL,
   DESCRIPTION VARCHAR(255),
   IS_ACTIVE BOOLEAN,
   CONSTRAINT PK_TB_PAYMENT_METHOD PRIMARY KEY (ID)
);

CREATE TABLE TB_PRODUCT (
  ID BIGINT NOT NULL,
   TITLE VARCHAR(255),
   PRICE DECIMAL(11, 2),
   BRAND VARCHAR(255),
   STOCK_AMOUNT INTEGER,
   IS_ACTIVE BOOLEAN,
   CONSTRAINT PK_TB_PRODUCT PRIMARY KEY (ID)
);

CREATE TABLE TB_TREATMENT (
  ID BIGINT NOT NULL,
   DESCRIPTION VARCHAR(255) NOT NULL,
   PRICE DECIMAL(11, 2) NOT NULL,
   IS_ACTIVE BOOLEAN NOT NULL,
   CONSTRAINT PK_TB_TREATMENT PRIMARY KEY (ID)
);

CREATE TABLE TB_TREATMENT_PRODUCT (
  ID BIGINT NOT NULL,
   DESCRIPTION VARCHAR(255),
   IS_ACTIVE BOOLEAN,
   CONSTRAINT PK_TB_TREATMENT_PRODUCT PRIMARY KEY (ID)
);

CREATE TABLE TB_USER (
  ID BIGINT NOT NULL,
   NAME VARCHAR(255),
   EMAIL VARCHAR(255),
   PASSWORD VARCHAR(255),
   IS_ADMIN BOOLEAN,
   IS_ACTIVE BOOLEAN,
   PHONE VARCHAR(255),
   CPF VARCHAR(255),
   RG VARCHAR(255),
   ADDRESS_ID BIGINT,
   ACCESS_LEVEL_ID BIGINT,
   CONSTRAINT PK_TB_USER PRIMARY KEY (ID)
);

CREATE SEQUENCE IF NOT EXISTS SEQ_ACCESS_LEVEL START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS SEQ_ADDRESS START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS SEQ_CUSTOMER START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS SEQ_EMPLOYEE START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS SEQ_EXPENSE START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS SEQ_MESSAGE_TEMPLATE START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS SEQ_PAYMENT_METHOD START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS SEQ_PRODUCT START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS SEQ_TREATMENT START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS SEQ_TREATMENT_PRODUCT START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS SEQ_USER START WITH 1 INCREMENT BY 50;

ALTER TABLE TB_EMPLOYEE ADD CONSTRAINT FK_TB_EMPLOYEE_ON_USER FOREIGN KEY (USER_ID) REFERENCES TB_USER (ID);

ALTER TABLE TB_EMPLOYEE_TREATMENT ADD CONSTRAINT FK_EMPTRE_ON_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES TB_EMPLOYEE (ID);

ALTER TABLE TB_EMPLOYEE_TREATMENT ADD CONSTRAINT FK_EMPTRE_ON_TREATMENT FOREIGN KEY (TREATMENT_ID) REFERENCES TB_TREATMENT (ID);

ALTER TABLE TB_CUSTOMER ADD CONSTRAINT FK_TB_CUSTOMER_ON_USER FOREIGN KEY (USER_ID) REFERENCES TB_USER (ID);

ALTER TABLE TB_USER ADD CONSTRAINT UC_TB_USER_EMAIL UNIQUE (EMAIL);

ALTER TABLE TB_USER ADD CONSTRAINT FK_TB_USER_ON_ACCESS_LEVEL FOREIGN KEY (ACCESS_LEVEL_ID) REFERENCES TB_ACCESS_LEVEL (ID);

ALTER TABLE TB_USER ADD CONSTRAINT FK_TB_USER_ON_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES TB_ADDRESS (ID);